### ISSUE TITLE
Discount for TTC

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-price-calculator-ui#10]
A request from TTC counselor - to add fixed amount / percentage discount for TTC Stays.

**Comment by iswara108** [comment]
Started to work on branch add-discount-to-ttc.

**Comment by danthareja** [comment]
`TTC Graduate` - fixed 10% discount for course, yvp, accomodation

**Comment by danthareja** [comment]
@iswara108, Fixed in https://github.com/danthareja/sivananda-price-calculator-ui/commit/39db28e74b679d7176bc27442571e9115bf51063

I changed the UI a bit, let me know what you think.

**Comment by iswara108** [comment]
Superb !
