### ISSUE TITLE
Daily Total in Price Breakdown

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-price-calculator-ui#15]
Add a column to see daily total (Accommodation + YVP) inside the price breakdown.

Default price breakdown to be open as soon as querying for a reservation (so that the user doesn't have to press the "Price Breakdown" in order to open it, but he/she can close it and reopen if they wish)

**Comment by danthareja** [comment]
@iswara108, fixed in https://github.com/danthareja/sivananda-price-calculator-ui/commit/26d83614a317daeaf72af3543a904a9f4dbeeedf and https://github.com/danthareja/sivananda-price-calculator-ui/commit/0bde1c338cf5a22e2d20442719b7ca06b95e1ea8
