### ISSUE TITLE
Garden Room Shared (Whole) - doesn't display prices

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-price-calculator-ui#18]
When selecting room category "Garden Room Shared (whole)" the price is not changing accordingly. The previous price remains on the calculation.
![screenshot 2017-10-29 at 15 01 36](https://user-images.githubusercontent.com/9681451/32147212-1dde82c6-bcba-11e7-8c6b-8bc6415de1e0.png)

**Comment by danthareja** [comment]
Thanks for the report! This was a problem in the calculator library, and was fixed in
https://github.com/danthareja/sivananda-price-calculator/commit/4a01b29baef788d857405cabccd0379339f36a13
