### ISSUE TITLE
Dates Order

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-price-calculator-ui#20]
Dates are not displayed according to chronological order within a stay (perhaps across different stays also)

![img_20171102_085111](https://user-images.githubusercontent.com/9681451/32361164-8edac2ce-c033-11e7-901a-4d3a6c424e4c.jpg)

**Comment by danthareja** [comment]
Thanks for the report @iswara108

**Comment by danthareja** [comment]
Fixed in f89ac513086ba023faed46afdea48cb942d624da
