### ISSUE TITLE
Duplicate Dates

### ISSUE THREAD

**Issue by iswara108** [danthareja/sivananda-price-calculator-ui#7]
We should not allow duplicate dates, or gaps between stays.
There is a test case: 'duplicate days' that should not be allowed.

**Comment by danthareja** [comment]
@iswara108, the calculator library no longer allows duplicate dates https://github.com/danthareja/sivananda-price-calculator/commit/7e13cda4c67841b4e715c8e6a588cd2aa682c7a5#diff-413912d64cba4fe8f9ffe99a8dc30ccbR35

Now it's a matter of enforcing such rules on the client as well.

**Comment by danthareja** [comment]
Fixed in 5467d872434189362aab241eb71feedf9c3fa0aa
